bt_action_server:
  ros__parameters:
    action_name: "execute_tree"
    tick_frequency: 50
    ros_plugins_timeout: 1000
    groot2_port: 1667

    # BehaviorTree.ROS2 will scan these package-relative folders for BT plugins.
    plugins:
      - bt_actions/lib
      - bt_nodes_llm/lib

    # XML subtrees made available to TreeExecutionServer.
    behavior_trees:
      - bt_executor/trees

    # Custom parameters consumed by LLMTreeServer.
    publish_feedback: true
