bt_action_server:
  ros__parameters:
    action_name: "/bt_executor/execute_tree"
    tick_frequency: 20
    groot2_port: 1667
    ros_plugins_timeout: 10000
    behavior_trees:
      - "bt_executor/trees"

    # bt_executor custom parameters
    plugin_directories:
      - "robot_actions/lib"
    nav2_action_name: "/a200_0000/navigate_to_pose"
    log_temperature_service_name: "/log_temperature"
    take_picture_service_name: "/take_picture"
    status_topic: "/mission_coordinator/status_text"
    active_node_topic: "/mission_coordinator/active_subtree"
    auto_restart_on_failure: false
    feedback_rate_hz: 5.0
